# NumPy

참고 : 파이썬 데이터 사이언스 핸드북 80p-89p

In [1]:
import numpy as np

### 비교 연산자

In [2]:
x = np.array([1,2,3,4,5])

In [3]:
x < 3

array([ True,  True, False, False, False])

In [4]:
x > 3

array([False, False, False,  True,  True])

In [5]:
x <= 3

array([ True,  True,  True, False, False])

In [6]:
x >= 3

array([False, False,  True,  True,  True])

In [7]:
x != 3

array([ True,  True, False,  True,  True])

In [8]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

In [9]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [10]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

### 부울 배열 작업

요소 개수 세기

> .count_nonzero() <br>
> .sum() <br>
> .any() <br>
> .all()

In [11]:
np.count_nonzero(x < 6)

8

In [12]:
np.sum(x < 6)

8

In [13]:
## 각 행에 6보다 작은 값의 개수
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [14]:
## 8보다 큰 값이 하나라도 있는지
np.any(x > 8)

True

In [15]:
## 모든 값이 10보다 작은지
np.all(x < 10)

True

In [16]:
## 각 행의 모든 값이 8보다 작은지
np.all(x < 8, axis=1)

array([ True, False,  True])

부울 연산자

> & <br>
> | <br>
> ^ <br>
> ~ <br>

In [17]:
np.sum((x > 3) & (x < 8))

6

In [18]:
np.sum((x < 3) | (x > 8))

3

### 마스킹 연산

> 배열에서 조건에 맞는 값들을 선택할 때 부울 배열을 인덱스로 사용하는 것

In [19]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [20]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])